### ISSUE TITLE
1.11.2 - Issues starting on dedicated server

### ISSUE THREAD

**Issue by silent-mobious** [TeamMD5/NineTailLib#7]
Tried adding NineTailLib and ProjectX2 to an existing mod pack and created a new world, however during startup it's crashing.  Client runs fun, NineTailLib doesn't like dedicated servers?

**Mod Versions tested**: NineTailLib-1.11.2-1.6.138-universal, ProjectX-1.11.2-2.1.19-universal
**Forge version used**: forge-1.11.2-13.20.1.2414-universal
**Log**: [Pastebin of crash log](https://pastebin.com/dmpxeiVt)
Caused by: java.lang.RuntimeException: Attempted to load class byz for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
	... 42 more

Thanks!

**Comment by Adam8234** [comment]
This is part of ProjectX I'm sure. Checking into it quick

**Comment by Adam8234** [comment]
Yep. This should be moved to ProjectX. I don't have permission, so can you close this and I'll have it fixed in dev. Thanks for your report!

**Comment by silent-mobious** [comment]
This issue was moved to TeamMD5/ProjectX#4
